---
development:
  dialect: postgres
  database: verceldb
  user: default
  password: EX1h0ALrVSlD
  host: postgres://default:EX1h0ALrVSlD@ep-small-queen-a4gtvomp-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://default:EX1h0ALrVSlD@ep-small-queen-a4gtvomp.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://default:EX1h0ALrVSlD@ep-small-queen-a4gtvomp.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"}}
